### ISSUE TITLE
Some issue about the definition of the instance segmentation

### ISSUE THREAD

**Issue by ddghjikle** [Linwei-Chen/LIS#1]
Hi, thanks for sharing this wonderful work and codes. I am confused by the definition of instance segmentation in your work. According to my best knowledge, semantic segmentation is to segment objects of different classes. Furthermore, instance segmentation segments each object of the same class. Although the manuscript is named with instance segmentation, all visualizations in your manuscript look like results of semantic segmentation, as instances of the same class are not distinguished from each other.

**Comment by Linwei-Chen** [comment]
I have assigned a specific color to each class to provide a better visual comparison, which might be the source of your confusion. Bounding boxes are employed to distinguish each instance. If desired, you can modify the color of each instance.
