### ISSUE TITLE
About coco annotation json

### ISSUE THREAD

**Issue by SNOWandwhite** [Linwei-Chen/LIS#12]
The coco annotation json isn't existed in dataset which is downdloaded from BaiduDrive and GoogleDrive.

**Comment by Linwei-Chen** [comment]
Thanks for your interest! This is because we are hosting a challenge at CVPR 2024. You can provide your email address, and I will send it to you.

**Comment by SNOWandwhite** [comment]
> Thanks for your interest! This is because we are hosting a challenge at CVPR 2024. You can provide your email address, and I will send it to you.

My email is : asd530684966@163.com

**Comment by Linwei-Chen** [comment]
Sent~

**Comment by SNOWandwhite** [comment]
> Sent~

Thanks!

**Comment by Swafim** [comment]
Hello. Could you please also send the annotation files to me? My Email is zxvasdfqwr@126.com. Thanks!
