### ISSUE TITLE
About Pytorch version

### ISSUE THREAD

**Issue by Mitsualfa** [Linwei-Chen/LIS#3]
I tried to reproduce your work, but the lower version of Pytorch/CUDA computing power does not match the graphics card of RTX3090. The higher version of Pytorch has difficulty installing mmcv-full (requires 1.3.8~1.4.0) that is compatible with mmdet. I would like to ask which version of Python/CUDA/mmcv you used before?

**Comment by Linwei-Chen** [comment]
torch 1.7.1, this site may help: https://mmcv.readthedocs.io/en/v1.4.1/get_started/installation.html
