### ISSUE TITLE
特征图可视化问题

### ISSUE THREAD

**Issue by MrWan001** [Linwei-Chen/LIS#5]
作者您好，想请教下论文中图2的特征图是用什么方式画的，分割网络的中间层通道一般64或者128这样的，画出图2这样的图需要怎样处理，是通过PCA降维到3通道然后画出rgb的图吗

**Comment by Linwei-Chen** [comment]
PCA也可以试试，更简单的方式是通道维度的均值，然后用热力图的colormap映射
