### ISSUE TITLE
About the version of mmcv and mmdet

### ISSUE THREAD

**Issue by stephenwang0317** [Linwei-Chen/LIS#6]
Could you please provide information on the recommended versions of mmcv and mmdet for compatibility with the project?

I have encountered the following error when I run the code:
```
ImportError: cannot import name 'filter_scores_and_topk' from 'mmdet.core.utils'
```

This error occurs with the following versions:

mmcv-full version: **1.3.18**
mmdet version: **2.14.0**

Thank you very much for your time and assistance. I appreciate your help in resolving this matter.

**Comment by Linwei-Chen** [comment]
I used mmcv-full==1.4.0 and mmdet==2.15.1 for your reference.

**Comment by stephenwang0317** [comment]
> I used mmcv-full==1.4.0 and mmdet==2.15.1 for your reference.

Thanks a lot.
