### ISSUE TITLE
Baidu Drive URL failure

### ISSUE THREAD

**Issue by Hanqing-Sun** [Linwei-Chen/LIS#9]
The provided URL for Baidu Drive says the share has been canceled.
After reading #8, may I know the schedule for recovering the share link?

**Comment by Linwei-Chen** [comment]
Hi, thanks for your attention! You can access the dataset through the temporary (7-day) link: https://pan.baidu.com/s/1GKoVHUcaRfEp-DM1WIrymw with the code: 46u8.

**Comment by Hanqing-Sun** [comment]
Downloading started👏
LIS is an interesting work. Thank you.
